spring:
  liquibase:
    change-log:  classpath:db/liquibase-changelog-test.xml
  datasource:
    platform: h2 
    url: jdbc:h2:mem:testdb 
    driverClassName: org.h2.Driver
    username:
    password:
   